# Generated by Django 3.2.12 on 2022-03-15 14:43

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=50, null=True, unique=True)),
                ('noc_operator', models.CharField(max_length=100)),
                ('field_supervisor', models.CharField(max_length=100)),
                ('zonal_manager', models.CharField(max_length=100)),
                ('zone', models.CharField(choices=[('Coastal', 'Coastal'), ('Northern', 'Northern'), ('Southern', 'Southern')], max_length=20)),
                ('maintanance_partner', models.CharField(default='PIVOTECH', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteinfo.continent')),
            ],
        ),
        migrations.CreateModel(
            name='FE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('GMT', models.CharField(blank=True, max_length=20, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteinfo.cluster')),
            ],
            options={
                'verbose_name': 'Field Engineer',
                'verbose_name_plural': 'Field Engineers',
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('HTA_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('tenant_ID', models.CharField(max_length=10)),
                ('site_name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Dar es salaam', 'Dar es salaam'), ('Tanga', 'Tanga'), ('Pwani', 'Pwani'), ('Lindi', 'Lindi'), ('Mtwara', 'Mtwara'), ('Ruvuma', 'Ruvuma'), ('Morogoro', 'Morogoro')], max_length=20, null=True)),
                ('grid_status', models.CharField(choices=[('Off Grid', 'Off Grid'), ('Grid', 'Grid')], max_length=10, null=True)),
                ('configuration', models.CharField(choices=[('GHS', 'GHS'), ('GHX', 'GHX'), ('GXX', 'GXX'), ('OHS', 'OHS'), ('OHX', 'OHX'), ('OXX', 'OXX')], max_length=3, null=True)),
                ('dg_ownership', models.CharField(choices=[('HTT-DG', 'HTT-DG'), ('LL-DG', 'LL-DG'), ('NON-DG', 'NON-DG')], max_length=10, null=True)),
                ('site_class', models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=10, null=True)),
                ('luku_payment', models.CharField(choices=[('Post-Paid', 'Post-Paid'), ('Pre-Paid', 'Pre-Paid'), ('Off-Grid', 'Off-Grid'), ('LandLord', 'LandLord'), ('Consolidated', 'Consolidated')], max_length=20, null=True)),
                ('site_status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10, null=True)),
                ('QSV', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=4, null=True)),
                ('site_type', models.CharField(choices=[('IBS', 'IBS'), ('Roof Top', 'Roof Top'), ('Green Field', 'Green Field')], max_length=30, null=True)),
                ('criticality', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True)),
                ('dg_present', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('DG_type', models.CharField(max_length=50, null=True)),
                ('meter_number', models.IntegerField(blank=True, null=True)),
                ('luku_cph', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fuel_cph', models.DecimalField(decimal_places=1, max_digits=3)),
                ('MKII_PLC', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('PLC_locked', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('dg_capacity', models.IntegerField()),
                ('tank_capacity', models.IntegerField(null=True)),
                ('ETA', models.TimeField()),
                ('ERT', models.TimeField()),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cluster', to='siteinfo.cluster')),
                ('field_engineer', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cluster', chained_model_field='cluster', on_delete=django.db.models.deletion.CASCADE, to='siteinfo.fe')),
                ('fuel_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FuelStation', to='siteinfo.fuelstation')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteinfo.continent')),
                ('country', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='continent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='siteinfo.country')),
            ],
        ),
    ]
