# Generated by Django 3.2.12 on 2022-03-15 15:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_engineer', models.CharField(max_length=30, unique=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('GMT', models.CharField(blank=True, max_length=20, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteinfo.cluster')),
            ],
            options={
                'verbose_name': 'Field Engineer',
                'verbose_name_plural': 'Field Engineers',
            },
        ),
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='fe',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='location',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.AddField(
            model_name='site',
            name='access_restricted',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='restriction_reasons',
            field=models.CharField(blank=True, choices=[('Safety Reasons', 'Safety Reasons'), ('Permit Reasons', 'Permit Reasons'), ('No Restriction', 'No Restriction')], default='No Restriction', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterField(
            model_name='site',
            name='field_engineer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cluster', chained_model_field='cluster', on_delete=django.db.models.deletion.CASCADE, to='siteinfo.fieldengineer'),
        ),
        migrations.DeleteModel(
            name='FE',
        ),
    ]
