# Generated by Django 3.2.12 on 2022-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='fuel_cph',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='site',
            name='luku_cph',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
