# Generated by Django 3.2.12 on 2022-03-12 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteinfo', '0002_auto_20220312_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='cluster_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
