# Generated by Django 3.2.12 on 2022-03-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0002_auto_20220315_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50, null=True, unique=True)),
                ('plate_number', models.CharField(max_length=10, null=True, unique=True)),
                ('vehicle_status', models.CharField(blank=True, choices=[('In Service', 'In Service'), ('Out Service', 'Out of Service')], default='In Service', max_length=50, null=True)),
                ('field_engineer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteinfo.fieldengineer')),
            ],
        ),
    ]
