# Generated by Django 3.2.12 on 2022-03-16 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0003_fleetvehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleetvehicle',
            options={'verbose_name': 'Fleet Vehicle', 'verbose_name_plural': 'Fleet Vehicles'},
        ),
        migrations.AddField(
            model_name='fieldengineer',
            name='alternate_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fieldengineer',
            name='plate_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteinfo.fleetvehicle'),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='phone_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='site',
            name='anchor_tenant',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='number_of_tenants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='tanesco_region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fleetvehicle',
            name='vehicle_status',
            field=models.CharField(blank=True, choices=[('In Service', 'In Service'), ('Out of Service', 'Out of Service')], default='In Service', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
