# Generated by Django 3.2.12 on 2022-03-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0004_alter_cluster_cluster_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='cluster_manager',
        ),
    ]
