# Generated by Django 3.2.12 on 2022-03-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0005_rename_plate_number_fieldengineer_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetvehicle',
            name='car_ownership',
            field=models.CharField(blank=True, choices=[('Leased', 'Leased'), ('Owned', 'Owned')], default='Owned', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='SPA_Status',
            field=models.CharField(choices=[('Configured', 'Configured'), ('Non-Configured', 'Non-Configgured'), ('Optimized', 'Optimized')], default='Optimized', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_load',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
