# Generated by Django 3.2.12 on 2022-03-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0005_remove_cluster_cluster_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cluster', to='siteinfo.cluster'),
        ),
        migrations.AlterField(
            model_name='site',
            name='fuel_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FuelStation', to='siteinfo.fuelstation'),
        ),
        migrations.CreateModel(
            name='FE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, max_length=10, null=True, unique=True)),
                ('GMT', models.CharField(blank=True, max_length=20, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FeCluster', to='siteinfo.cluster')),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='field_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FieldEngineer', to='siteinfo.fe'),
        ),
    ]
