# Generated by Django 3.2.12 on 2022-03-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0006_auto_20220313_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fe',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
