# Generated by Django 3.2.12 on 2022-03-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0007_auto_20220316_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleetvehicle',
            old_name='plate_number',
            new_name='registration_number',
        ),
        migrations.RemoveField(
            model_name='fleetvehicle',
            name='field_engineer',
        ),
    ]
