# Generated by Django 3.2.12 on 2022-03-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0007_alter_fe_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fe',
            options={'verbose_name': 'Field Engineer', 'verbose_name_plural': 'Field Engineers'},
        ),
        migrations.AlterField(
            model_name='fe',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteinfo.cluster'),
        ),
    ]
