# Generated by Django 3.2.12 on 2022-03-13 19:44

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0008_auto_20220313_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='field_engineer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cluster', chained_model_field='cluster', null=True, on_delete=django.db.models.deletion.CASCADE, to='siteinfo.cluster'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10, null=True),
        ),
    ]
