# Generated by Django 3.2.12 on 2022-03-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0010_alter_site_field_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_shelter',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Outdoor', max_length=50, null=True),
        ),
    ]
