# Generated by Django 3.2.12 on 2022-03-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0011_site_site_shelter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('zone', models.CharField(choices=[('Coastal', 'Coastal'), ('Northern', 'Northern'), ('Southern', 'Southern')], default='Coastal', max_length=50)),
                ('LegacySiteID', models.CharField(max_length=50)),
                ('SiteName', models.CharField(max_length=50)),
                ('GeneratorRunDHM', models.CharField(max_length=50)),
                ('GeneratorRunMinutes', models.CharField(max_length=50)),
                ('CummulativeRunningDHM', models.CharField(max_length=50)),
                ('CummulativeRunningMinutes', models.CharField(max_length=50)),
                ('GeneratorStopMinutes', models.CharField(max_length=50)),
                ('GeneratorStopDHM', models.CharField(max_length=50)),
                ('CummulativeStopMinutes', models.CharField(max_length=50)),
                ('CummulativeStopDHM', models.CharField(max_length=50)),
                ('datasourcename', models.CharField(max_length=50)),
                ('HTT_TrialSite', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Relay Data',
                'verbose_name_plural': 'Relay Data',
            },
        ),
    ]
