# Generated by Django 3.2.12 on 2022-03-14 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0025_alter_site_field_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='field_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FieldEngineer', to='siteinfo.fe'),
        ),
    ]
